FROM python:alpine
RUN apk --no-cache add curl tzdata libpq build-base
WORKDIR /app

COPY requirements_arm32.txt .
RUN pip install --upgrade pip && pip install -r requirements_arm32.txt && pip install gunicorn

COPY /BeatLog/ ./beatlog

ENTRYPOINT gunicorn -w 3 -b 0.0.0.0:8000 --preload 'beatlog:create_app()'