FROM python:3.10-alpine
RUN apk --no-cache add curl tzdata libpq build-base
WORKDIR /app

RUN pip install --upgrade pip setuptools wheel pip && pip install Flask python-dotenv psycopg psycopg_pool Flask-APScheduler geoip2 gunicorn

COPY /BeatLog/ ./beatlog

ENTRYPOINT gunicorn -w 3 -b 0.0.0.0:8000 --preload 'beatlog:create_app()'